import Head from "next/head";

import Header from "../components/header/Header";
import Nav from "../components/nav/Nav";
import Results from "../components/results/Results";

import { requests } from "../util/requests";

const Home = ({ results }) => {
	return (
		<div>
			<Head>
				<title>Hulu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Header */}
			<Header />
			{/* Nav */}
			<Nav />
			{/* Results */}
			<Results results={results} />
		</div>
	);
};

export async function getServerSideProps(context) {
	const genre = context.query.genre;

	const request = await fetch(requests[genre]?.url || requests.fetchTrending.url);
	const data = await request.json();

	return {
		props: data,
	};
}

export default Home;
